EMAIL='//*[@id="username"]'
PASSWORD='//*[@id="password"]'
CLOSE_BUTTON='/html/body/div[4]/div/div/div/div[2]/div/div/button'
BANNER_CLOSE_BUTTON ='/html/body/div[3]/div[1]/div[2]/button'
ADD_TO_CART="/html/body/div[3]/div/main/div/section/div[2]/div[4]/div[2]/div[2]/div[1]/button/div"
SUBTOTAL='/html/body/div[4]/div/div/div/div/div/div/div/div[2]/div[2]/div[2]/div/span/span[3]'
CART = '/html/body/header/div[2]/nav/div/div/div[5]/div[3]/div/div/button'
COUNTER= '/html/body/div[4]/div/div/div/div/div/div/div/div[2]/div[1]/div[2]/div/ul/li/div/div[2]/div[2]/div[1]/button[1]'
COMPLETE_PURCHASE='/html/body/div[4]/div/div/div/div/div/div/div/div[2]/div[2]/div[3]/a[1]'
CHECKOUT = '/html/body/div[3]/div/div/div/div[1]/div/div/form/div/div[5]/button'
TERMS='//*[@id="default-checkbox"]'
COMPLETE_ORDER='/html/body/div[3]/div/div/div/div[1]/div/div/form/div[2]/div[2]/button'
COD='/html/body/div[3]/div/div/div/div[1]/div/div/form/div[2]/ul/li[2]/label/div/span'
ORDER_NUMBER='/html/body/div[3]/section/div/div/div[3]/div[2]/div/div/div[1]/h2'